# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_goal_task_taskconstraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAllotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='goal',
            name='default_location',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='timeallotment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Task'),
        ),
    ]
