# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170427_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
    ]
